# Generated by Django 5.0.7 on 2024-07-27 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models

def seed_mymodel(apps, schema_editor):
    Field = apps.get_model('form', 'Field')
    
    data = [
        {'option': 'text_field'},
        {'option': 'dropdown_field'},
        {'option': 'checkbox_field'},
    ]
    
    for entry in data:
        Field.objects.get_or_create(**entry)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number_of_steps', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('new', 'New'), ('draft', 'Draft'), ('current', 'Current'), ('past', 'Past')], default='new', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='form.form')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RunPython(seed_mymodel),
    ]
