# Generated by Django 5.0.7 on 2024-07-27 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_form_created_at_form_updated_at_step_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='form.field'),
            preserve_default=False,
        ),
    ]
