# Generated by Django 5.0.7 on 2024-07-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_section_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='style',
            field=models.TextField(),
        ),
    ]
